
###
GET http://localhost:8080/tmp/1

###

POST http://localhost:8080/tmp
Content-Type: application/json

{
  "id":"1",
  "data2":"5"
}

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{fetchUser(arg0: 1){id}}"
}

###

POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query SearchDoc($filter: IdDocumentFilter) {searchDoc(arg0: $filter){id}}",
  "variables": {
    "filter": {
    }
  }
}

###

POST http://127.0.0.1:8080/cars
Content-Type: application/json

{
  "id": 1,
  "model": "toyota",
  "engine": "v5",
  "amount": "1"
}

###

GET http://127.0.0.1:8080/cars/1

###